coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
