language: cpp
compiler:
  - gcc
  - clang
before_script:
  - '[[ $CXX != "clang" ]]' # Clang 3.2 not yet supported
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
  - sudo apt-get -qq update
  - '[[ $CXX == "g++" ]] && sudo apt-get -qq install g++-4.7 && export CXX=g++-4.7 && export CC=gcc-4.7'
  - sudo apt-get -qq install libboost1.50-all-dev
  - ./tools/travis-build-setup
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - vallentin@icir.org
  email:
    on_success: change
    on_failure: always
env:
  global:
    # The prefix for VAST dependencies.
    - PREFIX=$HOME/builds/mavam/prefix
  matrix:
    - BUILD_TYPE=--enable-debug
matrix:
  allow_failures:
    - compiler: clang
