language: cpp
compiler:
  - gcc
#  - clang
before_script:
  - ./tools/travis-build-setup
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - vallentin@icir.org
  email:
    on_success: change
    on_failure: always
