language: cpp
compiler:
  - gcc
  - clang
before_script:
  # Get a recent GCC.
  - echo "\n" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.7
  - g++ --version
  # Boost
  #- apt-get install libboost-filesystem-dev libboost-system-dev libboost-regex-dev libbost-program-options-dev
  # Libcppa
  - export PREFIX=$HOME/builds/mavam/prefix
  - git clone git://github.com/Neverlord/libcppa.git && cd libcppa
  - ./configure --enable-debug --prefix=$PREFIX
  - make install
  - cd ..
  # 0event
  - git clone git://github.com/mavam/ze.git && cd ze
  - ./configure --enable-debug --prefix=$PREFIX
  - make install
  - cd ..
  # Configure VAST
  - ./configure --enable-debug --with-libcppa=$PREFIX --with-0event=$PREFIX
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - vallentin@icir.org
  email:
    on_success: change
    on_failure: always
