language: cpp
compiler:
  - gcc
  - clang
before_script:
  - ./tools/travis-build-setup
  - ./configure --enable-debug --with-libcppa=$PREFIX --with-0event=$PREFIX
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - vallentin@icir.org
  email:
    on_success: change
    on_failure: always
