notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master

language: cpp

compiler:
#  - gcc
  - clang

env:
  global:
    - PREFIX=$HOME/builds/mavam/prefix # The prefix for dependencies.
    - PATH=$PREFIX/bin:$PATH
    - LD_LIBRARY_PATH=$PREFIX/lib
    - CONCURRENCY=4
  matrix:
    - BUILD_TYPE=--enable-debug

#matrix:
#  allow_failures:
#    - compiler: gcc

before_script:
  - sh .travis.prepare
  - ./configure $BUILD_TYPE --prefix=$PREFIX

script:
# This currently fails because there is not enough memory available on the
# Travis (only 3GB), resulting in a segfault during the compilation process.
  - make -j $CONCURRENCY
  - build/bin/unit-test -v 3
