language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
  - sudo add-apt-repository -y \
    "deb http://archive.ubuntu.com/ubuntu/ quantal main universe" # Boost 1.50
  - sudo apt-get -qq update
  - '[[ $CXX == "clang" ]] && exit 1 || [[ $CXX == "g++" ]] \
      && sudo apt-get -qq install g++-4.7 \
      && export CXX=g++-4.7 \
      && export CC=gcc-4.7'
  - sudo apt-get -qq install libboost1.50-all-dev
  # Libcppa
  - git clone git://github.com/Neverlord/libcppa.git
  - pushd libcppa
  - ./configure --enable-debug --prefix=$PREFIX
  - make install
  - popd
  # 0event
  - git clone git://github.com/mavam/ze.git
  - pushd ze
  - ./configure --enable-debug --prefix=$PREFIX
  - make install
  - popd
  # VAST
  - ./configure $BUILD_TYPE --with-libcppa=$PREFIX --with-0event=$PREFIX
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - vallentin@icir.org
  email:
    on_success: change
    on_failure: always
env:
  global:
    # The prefix for VAST dependencies.
    - PREFIX=$HOME/builds/mavam/prefix
  matrix:
    - BUILD_TYPE=--enable-debug
matrix:
  allow_failures:
    - compiler: clang
