name: Feature Request
description: Request a new feature
title: "Feature Request Title"
body:
  - type: textarea
    attributes:
      label: Use Case
      description: A concise description of the problem to be addressed by this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Description
      description: A concise description of your preferred solution.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images, recordings, or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
