name: 'VAST Changelog'
on:
  pull_request:

jobs:
  update:
    name: 'Update'
    runs-on: ubuntu-20.04
    container: debian:buster-backports
    steps:
      - name: 'Install Dependencies'
        run: |
          apt-get update
          apt-get -y install git libsnappy-dev libbrotli-dev zlib1g-dev wget \
            liblz4-dev libzstd-dev ninja-build libpcap-dev libssl-dev \
            libbenchmark-dev libflatbuffers-dev  flatbuffers-compiler-dev \
            libyaml-cpp-dev libsimdjson-dev gnupg2 gcc-8 g++-8 python3 \
            python3-pip python3-venv jq software-properties-common
          apt-get -y -t buster-backports install libspdlog-dev libfmt-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade cmake
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: 'Configure Build'
        env:
          CC: gcc-8
          CXX: g++-8
        run: |
          ./configure --with-bundled-caf --without-arrow
      - name: 'Generate CHANGELOG.md'
        run: |
          cmake --build build --target changelog
      - name: 'Check CHANGELOG.md'
        run: |
          alias is_unchanged="git diff --exit-code $(git merge-base 'origin/${{ github.event.pull_request.base.ref }}' HEAD) --"
          if is_unchanged cmake/VASTVersionFallback.cmake; then
            # CHANGELOG.md must not be modified in non-release PRs
            is_unchanged CHANGELOG.md
          else
            # CHANGELOG.md must be modified in release PRs
            ! is_unchanged CHANGELOG.md
            # Check whether the updated CHANGELOG.md is correct
            cmake --build build --target update-changelog
            git diff-index --exit-code HEAD -- CHANGELOG.md
          fi
