name: Docs

on:
  push:
    branches:
      - master
      - v*
  pull_request:

jobs:
  test-docs:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: docs/yarn.lock
          cache: yarn
      - name: Install dependencies
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: docs
        run: yarn build

  deploy-docs:
    name: Deploy Docs
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs:
      - test-docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: docs/yarn.lock
          cache: yarn
      - name: Install dependencies
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: docs
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          user_name: tenzir-bot
          user_email: engineering@tenzir.com
