name: "Style Check"
on: push
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        ref: ${{ github.ref }}
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Diff local changes
      run: git diff -U0 --no-color $(git merge-base origin/master HEAD) | scripts/clang-format-diff.py -p1
